/**
 * @fileoverview This file defines the User model schema for the MediHack application using Mongoose.
 * The User model includes fields for username, password, admin status, email, experience points (xp), level, and coins.
 * It also includes timestamps for when the user was created and last updated.
*/
import mongoose from "mongoose";

/**
 * @typedef {Object} User
 * @property {string} username - The username of the user. Must be unique and is required.
 * @property {string} password - The password of the user. Required.
 * @property {boolean} isAdmin - Indicates if the user has admin privileges. Defaults to false.
 * @property {string} email - The email of the user. Must be unique and is required.
 * @property {number} xp - The experience points of the user. Defaults to 0.
 * @property {number} level - The level of the user. Defaults to 1.
 * @property {number} coins - The number of coins the user has. Defaults to 0.
 * @property {Date} createdAt - The date when the user was created. Automatically generated by Mongoose.
 * @property {Date} updatedAt - The date when the user was last updated. Automatically generated by Mongoose.
*/

const UserSchema = new mongoose.Schema({
    username: {
        type: String,
        required: true,
        unique: true
    },
    password: {
        type: String,
        required: true,
    },
    isAdmin: {
        type: Boolean,
        default: false
    },
    email: {
        type: String,
        required: true,
        unique: true
    },
    xp: {
        type: Number,
        default: 0
    },
    level: {
        type: Number,
        default: 1
    },
    coins: {
        type: Number,
        default: 0
    },
}, { timestamps: true });

export default mongoose.model("User", UserSchema);